### ISSUE TITLE
Highlighting items on mode line

### ISSUE THREAD

**Issue by issue-dispenser** [donderom/jazz-theme#7]
When moving the mouse cursor over an item in the mode line, the item gets truncated by the background highlight. Items that are just a single character turn invisible entirely.

Example:

![cut](https://cloud.githubusercontent.com/assets/13922417/9426007/f79a2480-48e4-11e5-827e-dfbdfafb1adf.png)

**Comment by donderom** [comment]
Could you please tell me the Emacs version and OS?

**Comment by issue-dispenser** [comment]
It happens on both Emacs 24.4.1 on Debian Jessie and 24.5.1 on Debian stretch.

**Comment by donderom** [comment]
Please try the latest version, I've removed unnecessary decoration in the mode-line.

**Comment by donderom** [comment]
Nevermind, I removed the wrong thing.

**Comment by issue-dispenser** [comment]
That didn't fix it for me, I'm afraid. I also happened to try it on Windows 7 (24.5.1 MinGW) with the same results.

**Comment by issue-dispenser** [comment]
Just to note, removing the line widths found in https://github.com/donderom/jazz-theme/blob/master/jazz-theme.el#L140-L146 fixed the issue, at the cost of removing the padding of the mode line (which does look nice). Is there a way to keep this padding without messing up the highlighting?

**Comment by donderom** [comment]
Good question. I don't want to sacrifice the padding. I never hover the mouse over the mode line so could you please tell me why do you need this in the first place?

**Comment by issue-dispenser** [comment]
It's not something that I need or see often, but it is a bit jarring when it does happen. It's just a minor annoyance, really. The rest of the theme is good.
