### ISSUE TITLE
Ediff hunks looks unreadable for string literals

### ISSUE THREAD

**Issue by edvorg** [donderom/jazz-theme#8]
![screenshot](https://dl.dropboxusercontent.com/s/sxfuj1po1qkxppx/Screenshot%202015-09-04%2011.54.42.png)

**Comment by donderom** [comment]
Oops, the screenshot is not available anymore :cry:

**Comment by edvorg** [comment]
sorry, if mistakenly removed it from dropbox. fixed

**Comment by donderom** [comment]
That's how it looks for me:
<img width="270" alt="ediff-files" src="https://cloud.githubusercontent.com/assets/274926/9787925/50d4d420-57cf-11e5-9e23-42ca8ceb7c82.png">
Any ideas how to reproduce it?

**Comment by edvorg** [comment]
Hmm. Maybe it clashes with something in my configuration. I will try to figure it out.

**Comment by edvorg** [comment]
Also, thank you for this project, it's my favourite theme for emacs. :+1:

**Comment by donderom** [comment]
Thanks!

**Comment by donderom** [comment]
Let me ask if you have figured it out?

**Comment by edvorg** [comment]
unfortunately no, bug is still present. here is my face definition

![screenshot](https://dl.dropboxusercontent.com/s/u7kmq6f65tu8muo/Screenshot%202015-11-06%2021.15.42.png)

could you please provide yours?
