### ISSUE TITLE
Highlighting in show-paren-mode Is Not Very Visible

### ISSUE THREAD

**Issue by noctuid** [donderom/jazz-theme#9]
First of all, I'd like to say that this is the first theme that I've really liked in emacs. It is by far my favourite.

The only problem I've noticed so far is that the highlighting of matching parens is almost unnoticeable for me. The background shade does not change very much, and while the matching parens do turn blue, I'm using rainbow parens, so this doesn't really set the matching paren apart (especially when it is right next to a paren of the same shade of blue).

**Comment by donderom** [comment]
Thanks! What do you suggest?

**Comment by noctuid** [comment]
I don't really like having a lighter background (a lot of themes do a light gray or blue). I think adding a lighter magenta to the palette and using that for the foreground might be a good change. For example, I think using `#AF4981` for the foreground of show-paren-match looks nice (and visible). Changing the background slightly might be nice as well, for example to `jazz-bg-1`.

**Comment by issue-dispenser** [comment]
FWIW, I think it should go a bit brighter than `#AF4981` since at least on my screen it is somewhat close to the `jazz-magenta` that's used for the 4th parenthesis pair (though it's better than the difference in the first pair as it stands now).
Changing just the foreground to something a tad brighter like `#c34c8f` seems to work better on my end.

**Comment by noctuid** [comment]
`#c34c8f` looks nice as well and more visible for me on low brightness. :+1:

**Comment by iAmMrinal0** [comment]
Any updates on this?

**Comment by donderom** [comment]
It's an old one, if anybody is still interested what about not changing colors but adding underline to matching parens?

**Comment by noctuid** [comment]
I don't really like underlines on parens personally, but that would work as well.
